INSERT INTO cards (
    hp, name, type, stage, evolves_from, description, weakness, weakness_multiplier,
    resistance, resistance_value, retreat_cost, illustrator, collection_code, collection_id, year
) VALUES
(60, 'Bulbasaur', 'Grass', 'basic', NULL, 'Seed Pokémon', 'Fire', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 1', 1, 2000),
(50, 'Charmander', 'Fire', 'basic', NULL, 'Lizard Pokémon', 'Water', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 2', 2, 2000),
(40, 'Squirtle', 'Water', 'basic', NULL, 'Tiny Turtle Pokémon', 'Lightning', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 3', 3, 2000),
(70, 'Pikachu', 'Lightning', 'basic', NULL, 'Mouse Pokémon', 'Fighting', 'x2', 'Metal', '-30', 1, 'Ken Sugimori', 'Set 4', 4, 2000),
(80, 'Machop', 'Fighting', 'basic', NULL, 'Superpower Pokémon', 'Psychic', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 5', 5, 2000),
(90, 'Gastly', 'Psychic', 'basic', NULL, 'Gas Pokémon', 'Darkness', 'x2', NULL, NULL, 0, 'Ken Sugimori', 'Set 6', 6, 2000),
(100, 'Meowth', 'Colorless', 'basic', NULL, 'Scratch Cat Pokémon', 'Fighting', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 7', 7, 2000),
(110, 'Magnemite', 'Metal', 'basic', NULL, 'Magnet Pokémon', 'Fighting', 'x2', 'Lightning', '-20', 1, 'Ken Sugimori', 'Set 8', 8, 2000),
(120, 'Zubat', 'Darkness', 'basic', NULL, 'Bat Pokémon', 'Psychic', 'x2', NULL, NULL, 0, 'Ken Sugimori', 'Set 9', 9, 2000),
(130, 'Clefairy', 'Fairy', 'basic', NULL, 'Fairy Pokémon', 'Metal', 'x2', 'Darkness', '-30', 1, 'Ken Sugimori', 'Set 10', 10, 2000),
(60, 'Oddish', 'Grass', 'basic', NULL, 'Weed Pokémon', 'Fire', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 11', 11, 2000),
(70, 'Vulpix', 'Fire', 'basic', NULL, 'Fox Pokémon', 'Water', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 12', 12, 2000),
(80, 'Poliwag', 'Water', 'basic', NULL, 'Tadpole Pokémon', 'Lightning', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 13', 13, 2000),
(90, 'Electabuzz', 'Lightning', 'basic', NULL, 'Electric Pokémon', 'Fighting', 'x2', 'Metal', '-30', 1, 'Ken Sugimori', 'Set 14', 14, 2000),
(100, 'Hitmonlee', 'Fighting', 'basic', NULL, 'Kicking Pokémon', 'Psychic', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 15', 15, 2000),
(110, 'Abra', 'Psychic', 'basic', NULL, 'Psi Pokémon', 'Darkness', 'x2', NULL, NULL, 0, 'Ken Sugimori', 'Set 16', 16, 2000),
(120, 'Snorlax', 'Colorless', 'basic', NULL, 'Sleeping Pokémon', 'Fighting', 'x2', NULL, NULL, 3, 'Ken Sugimori', 'Set 17', 17, 2000),
(130, 'Steelix', 'Metal', 'stage 1', 'Onix', 'Iron Snake Pokémon', 'Fire', 'x2', 'Grass', '-20', 4, 'Ken Sugimori', 'Set 18', 18, 2000),
(140, 'Umbreon', 'Darkness', 'stage 1', 'Eevee', 'Moonlight Pokémon', 'Fighting', 'x2', 'Psychic', '-30', 1, 'Ken Sugimori', 'Set 19', 19, 2000),
(150, 'Togepi', 'Fairy', 'basic', NULL, 'Spike Ball Pokémon', 'Metal', 'x2', 'Darkness', '-30', 1, 'Ken Sugimori', 'Set 20', 20, 2000),
(60, 'Chikorita', 'Grass', 'basic', NULL, 'Leaf Pokémon', 'Fire', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 21', 21, 2000),
(70, 'Cyndaquil', 'Fire', 'basic', NULL, 'Fire Mouse Pokémon', 'Water', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 22', 22, 2000),
(80, 'Totodile', 'Water', 'basic', NULL, 'Big Jaw Pokémon', 'Lightning', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 23', 23, 2000),
(90, 'Raichu', 'Lightning', 'stage 1', 'Pikachu', 'Mouse Pokémon', 'Fighting', 'x2', 'Metal', '-30', 2, 'Ken Sugimori', 'Set 24', 24, 2000),
(100, 'Machoke', 'Fighting', 'stage 1', 'Machop', 'Superpower Pokémon', 'Psychic', 'x2', NULL, NULL, 2, 'Ken Sugimori', 'Set 25', 25, 2000),
(110, 'Haunter', 'Psychic', 'stage 1', 'Gastly', 'Gas Pokémon', 'Darkness', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 26', 26, 2000),
(120, 'Persian', 'Colorless', 'stage 1', 'Meowth', 'Classy Cat Pokémon', 'Fighting', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 27', 27, 2000),
(130, 'Magneton', 'Metal', 'stage 1', 'Magnemite', 'Magnet Pokémon', 'Fighting', 'x2', 'Lightning', '-20', 2, 'Ken Sugimori', 'Set 28', 28, 2000),
(140, 'Golbat', 'Darkness', 'stage 1', 'Zubat', 'Bat Pokémon', 'Psychic', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 29', 29, 2000),
(150, 'Clefable', 'Fairy', 'stage 1', 'Clefairy', 'Fairy Pokémon', 'Metal', 'x2', 'Darkness', '-30', 2, 'Ken Sugimori', 'Set 30', 30, 2000),
(60, 'Gloom', 'Grass', 'stage 1', 'Oddish', 'Weed Pokémon', 'Fire', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 31', 31, 2000),
(70, 'Ninetales', 'Fire', 'stage 1', 'Vulpix', 'Fox Pokémon', 'Water', 'x2', NULL, NULL, 2, 'Ken Sugimori', 'Set 32', 32, 2000),
(80, 'Poliwhirl', 'Water', 'stage 1', 'Poliwag', 'Tadpole Pokémon', 'Lightning', 'x2', NULL, NULL, 2, 'Ken Sugimori', 'Set 33', 33, 2000),
(90, 'Electrode', 'Lightning', 'stage 1', 'Voltorb', 'Ball Pokémon', 'Fighting', 'x2', 'Metal', '-30', 1, 'Ken Sugimori', 'Set 34', 34, 2000),
(100, 'Hitmonchan', 'Fighting', 'basic', NULL, 'Punching Pokémon', 'Psychic', 'x2', NULL, NULL, 1, 'Ken Sugimori', 'Set 35', 35, 2000);

