INSERT INTO pokemon_attacks (card_id, name, cost, damage, description) VALUES
(1, 'Vine Whip', 'Grass', '20', 'Whips the foe with vines.'),
(2, 'Ember', 'Fire', '30', 'Burns the foe with flames.'),
(3, 'Bubble', 'Water', '10', 'Shoots bubbles to confuse the foe.'),
(4, 'Thunder Shock', 'Lightning', '30', 'May paralyze the foe.'),
(5, 'Karate Chop', 'Fighting', '40', 'A powerful martial arts move.'),
(6, 'Lick', 'Psychic', '10', 'May paralyze the foe with a lick.'),
(7, 'Scratch', 'Colorless', '20', 'Scratches the opponent.'),
(8, 'Magnet Bomb', 'Metal', '30', 'Launches a magnetic projectile.'),
(9, 'Bite', 'Darkness', '20', 'Bites the opponent.'),
(10, 'Fairy Wind', 'Fairy', '30', 'A gentle wind attack.'),
(11, 'Absorb', 'Grass', '10', 'Drains HP from the opponent.'),
(12, 'Flame Tail', 'Fire', '20', 'A fiery tail whip.'),
(13, 'Water Gun', 'Water', '20', 'Shoots water at the foe.'),
(14, 'Quick Attack', 'Lightning', '10', 'Hits first with a quick strike.'),
(15, 'Low Kick', 'Fighting', '30', 'A low, sweeping kick.'),
(16, 'Confuse Ray', 'Psychic', '10', 'May confuse the opponent.'),
(17, 'Body Slam', 'Colorless', '40', 'Slams the foe with full body weight.'),
(18, 'Iron Tail', 'Metal', '50', 'Hits with a steel-hard tail.'),
(19, 'Dark Pulse', 'Darkness', '60', 'Emits a dark shockwave.'),
(20, 'Sweet Kiss', 'Fairy', '10', 'May confuse the opponent.'),
(21, 'Razor Leaf', 'Grass', '30', 'Launches sharp-edged leaves.'),
(22, 'Flame Wheel', 'Fire', '40', 'Spins in flames to attack.'),
(23, 'Aqua Tail', 'Water', '50', 'Strikes with a water-covered tail.'),
(24, 'Volt Tackle', 'Lightning', '60', 'A high-voltage tackle.'),
(25, 'Submission', 'Fighting', '60', 'A reckless, full-body throw.');